### ISSUE TITLE
Mac OS 10.10.4: BleemSync issue on libcoreclr.dylib 

### ISSUE THREAD

**Issue by psk82** [pathartl/BleemSync#180]
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime Referenced from: /Users/xxxxxx/Downloads/PlayStationClassic/BleemSync/libcoreclr.dylib (which was built for Mac OS X 10.12)

I found this same issue on https://github.com/dotnet/cli/issues/6692
Question is, does the BleemSync script work just on 10.12?

**Comment by pathartl** [comment]
Yeah it may only work on 10.12+. Multiplatform is still pretty WIP

**Comment by electrovir** [comment]
Getting the same thing

```
lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Volumes/SONY/BleemSync/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Volumes/SONY/BleemSync/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by pathartl** [comment]
The way BleemSync runs has changed in 1.0.0 so this shouldn't be an issue anymore.
